### ISSUE TITLE
HandlerWithEvent type

### ISSUE THREAD

**Issue by siacomuzzi** [KolbySisk/next-route-handler-pipe#1]
Hi there 👋 

What's the reason to have the [HandlerWithEvent](https://github.com/KolbySisk/next-route-handler-pipe/blob/dc23eaa13dc440e587dd710c237be18c47fa6236/src/types.ts#L9) type?
Asking because, for api route handlers, I'd expect the [`context.params` object as 2nd argument](https://nextjs.org/docs/app/building-your-application/routing/route-handlers#dynamic-route-segments), instead of `NextFetchEvent`, [which is used for middleware functions](https://nextjs.org/docs/app/building-your-application/routing/middleware#waituntil-and-nextfetchevent).

```ts
// app/api/users/[id]/route.ts

import { pipe } from "next-route-handler-pipe";
import { catchErrors } from "@/middlewares";

async function handler(
  req: NextRequest,
  { params }: { params: { id: string } } // for handler functions, I'd expect this object instead of NextFetchEvent
) {
  const user = findUserById(params.id);
  // ...
}

export const GET = pipe(catchErrors, handler);
```

Or maybe I'm missing something?

Thanks!

**Comment by KolbySisk** [comment]
Yeah good catch, not sure how I missed this. Thanks for pointing it out. 

You can see the fix here: https://github.com/KolbySisk/next-route-handler-pipe/commit/6cce773a367922704ed4388af0731aa6c11f1118

It's been released as `2.0.0`
